### ISSUE TITLE
Have all the docker images of CN been deleted? When I use docker pull, I can't find the image of the specified version?

### ISSUE THREAD

**Issue by putianhui** [piraeusdatastore/piraeus-operator#200] opened 2021-07-19 02:26 UTC
```bash
[root@piraeus001 piraeus]# docker pull daocloud.io/piraeus/kube-scheduler-amd64
Using default tag: latest
Error response from daemon: manifest for daocloud.io/piraeus/kube-scheduler-amd64:latest not found: manifest unknown: manifest unknown
[root@piraeus001 piraeus]# docker pull daocloud.io/piraeus/csi-attacher:v3.0.2
Error response from daemon: manifest for daocloud.io/piraeus/csi-attacher:v3.0.2 not found: manifest unknown: manifest unknown
[root@piraeus001 piraeus]# docker pull daocloud.io/piraeus/livenessprobe:v2.1.0
Error response from daemon: manifest for daocloud.io/piraeus/livenessprobe:v2.1.0 not found: manifest unknown: manifest unknown
```

**Comment by WanzenBug** [comment] 2021-07-19 06:29
Duplicate of #191 I guess?

**Comment by putianhui** [comment] 2021-07-19 06:33
> 我猜是[#191 的](https://github.com/piraeusdatastore/piraeus-operator/issues/191)副本？

yes

I solved this problem. I uploaded all the images to my alicloud image warehouse

```bash

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/stork:2.5.0

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/kube-scheduler-amd64:v1.13.12

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/csi-attacher:v3.0.2

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/csi-node-driver-registrar:v2.0.1

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/csi-provisioner:v2.0.4

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/csi-resizer:v1.0.1

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/csi-snapshotter:v3.0.2

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/livenessprobe:v2.1.0

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/snapshot-controller:v3.0.2

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/drbd9-bionic:v9.0.27

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/piraeus-csi:v0.11.0

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/piraeus-ha-controller:v0.1.3

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/piraeus-operator:v1.3.1

registry.cn-zhangjiakou.aliyuncs.com/cmdsdis/piraeus-server:v1.11.1

```

**Comment by WanzenBug** [comment] 2021-07-19 06:35
In that case I'll move the discussion over to the older issue, closing this as a duplicate.

**Closed by WanzenBug** 2021-07-19 06:35 UTC
Labels: duplicate
