### ISSUE TITLE
linstor volume list command fails with NullPointerException

### ISSUE THREAD

**Issue by sribee** [piraeusdatastore/piraeus-operator#114] opened 2020-11-09 06:57 UTC
root@piraeus-op-cs-controller-595cdf94d6-nrzkz:/# linstor v l 
ERROR:
Show reports:
    linstor error-reports show 5FA8E4BB-00000-000031
root@piraeus-op-cs-controller-595cdf94d6-nrzkz:/# linstor error-reports show 5FA8E4BB-00000-000031
ERROR REPORT 5FA8E4BB-00000-000031

============================================================

Application:                        LINBIT�� LINSTOR
Module:                             Controller
Version:                            1.9.0
Build ID:                           678acd24a8b9b73a735407cd79ca33a5e95eb2e2
Build time:                         2020-09-23T09:33:23+00:00
Error time:                         2020-11-09 06:52:57
Node:                               piraeus-op-cs-controller-595cdf94d6-nrzkz

============================================================

Reported error:
===============

Category:                           RuntimeException
Class name:                         NullPointerException
Class canonical name:               java.lang.NullPointerException
Generated at:                       Method 'deviceProviderKindAsString', Source file 'Json.java', Line #73

Call backtrace:

    Method                                   Native Class:Line number
    deviceProviderKindAsString               N      com.linbit.linstor.api.rest.v1.serializer.Json:73
    apiToVolume                              N      com.linbit.linstor.api.rest.v1.serializer.Json:664
    lambda$apiToResourceWithVolumes$2        N      com.linbit.linstor.api.rest.v1.serializer.Json:477
    accept                                   N      java.util.stream.ReferencePipeline$3$1:195
    forEachRemaining                         N      java.util.ArrayList$ArrayListSpliterator:1655
    copyInto                                 N      java.util.stream.AbstractPipeline:484
    wrapAndCopyInto                          N      java.util.stream.AbstractPipeline:474
    evaluateSequential                       N      java.util.stream.ReduceOps$ReduceOp:913
    evaluate                                 N      java.util.stream.AbstractPipeline:234
    collect                                  N      java.util.stream.ReferencePipeline:578
    apiToResourceWithVolumes                 N      com.linbit.linstor.api.rest.v1.serializer.Json:506
    lambda$listVolumesApiCallRcWithToResponse$1 N      com.linbit.linstor.api.rest.v1.View:112
    accept                                   N      java.util.stream.ReferencePipeline$3$1:195
    forEachRemaining                         N      java.util.ArrayList$ArrayListSpliterator:1655
    copyInto                                 N      java.util.stream.AbstractPipeline:484
    wrapAndCopyInto                          N      java.util.stream.AbstractPipeline:474
    evaluateSequential                       N      java.util.stream.ReduceOps$ReduceOp:913
    evaluate                                 N      java.util.stream.AbstractPipeline:234
    collect                                  N      java.util.stream.ReferencePipeline:578
    lambda$listVolumesApiCallRcWithToResponse$2 N      com.linbit.linstor.api.rest.v1.View:113
    onNext                                   N      reactor.core.publisher.FluxFlatMap$FlatMapMain:378
    onNext                                   N      reactor.core.publisher.FluxContextStart$ContextStartSubscriber:96
    onNext                                   N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner:242
    onNext                                   N      reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber:385
    onNext                                   N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner:242
    request                                  N      reactor.core.publisher.Operators$ScalarSubscription:2317
    onSubscribeInner                         N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain:143
    onSubscribe                              N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner:237
    trySubscribeScalarMap                    N      reactor.core.publisher.FluxFlatMap:191
    subscribeOrReturn                        N      reactor.core.publisher.MonoFlatMapMany:49
    subscribe                                N      reactor.core.publisher.Flux:8311
    onNext                                   N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain:188
    request                                  N      reactor.core.publisher.Operators$ScalarSubscription:2317
    onSubscribe                              N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain:134
    subscribe                                N      reactor.core.publisher.MonoCurrentContext:35
    subscribe                                N      reactor.core.publisher.Flux:8325
    onNext                                   N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain:188
    onNext                                   N      reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber:121
    complete                                 N      reactor.core.publisher.Operators$MonoSubscriber:1755
    onComplete                               N      reactor.core.publisher.MonoStreamCollector$StreamCollectorSubscriber:167
    onComplete                               N      reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber:395
    onComplete                               N      reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner:252
    checkTerminated                          N      reactor.core.publisher.FluxFlatMap$FlatMapMain:838
    drainLoop                                N      reactor.core.publisher.FluxFlatMap$FlatMapMain:600
    innerComplete                            N      reactor.core.publisher.FluxFlatMap$FlatMapMain:909
    onComplete                               N      reactor.core.publisher.FluxFlatMap$FlatMapInner:1013
    onComplete                               N      reactor.core.publisher.FluxMap$MapSubscriber:136
    onComplete                               N      reactor.core.publisher.Operators$MultiSubscriptionSubscriber:1989
    onComplete                               N      reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber:78
    complete                                 N      reactor.core.publisher.FluxCreate$BaseSink:438
    drain                                    N      reactor.core.publisher.FluxCreate$BufferAsyncSink:784
    complete                                 N      reactor.core.publisher.FluxCreate$BufferAsyncSink:732
    drainLoop                                N      reactor.core.publisher.FluxCreate$SerializedSink:239
    drain                                    N      reactor.core.publisher.FluxCreate$SerializedSink:205
    complete                                 N      reactor.core.publisher.FluxCreate$SerializedSink:196
    apiCallComplete                          N      com.linbit.linstor.netcom.TcpConnectorPeer:455
    handleComplete                           N      com.linbit.linstor.proto.CommonMessageProcessor:363
    handleDataMessage                        N      com.linbit.linstor.proto.CommonMessageProcessor:287
    doProcessInOrderMessage                  N      com.linbit.linstor.proto.CommonMessageProcessor:235
    lambda$doProcessMessage$3                N      com.linbit.linstor.proto.CommonMessageProcessor:220
    subscribe                                N      reactor.core.publisher.FluxDefer:46
    subscribe                                N      reactor.core.publisher.Flux:8325
    onNext                                   N      reactor.core.publisher.FluxFlatMap$FlatMapMain:418
    drainAsync                               N      reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber:414
    drain                                    N      reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber:679
    onNext                                   N      reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber:243
    drainFused                               N      reactor.core.publisher.UnicastProcessor:286
    drain                                    N      reactor.core.publisher.UnicastProcessor:322
    onNext                                   N      reactor.core.publisher.UnicastProcessor:401
    next                                     N      reactor.core.publisher.FluxCreate$IgnoreSink:618
    next                                     N      reactor.core.publisher.FluxCreate$SerializedSink:153
    processInOrder                           N      com.linbit.linstor.netcom.TcpConnectorPeer:373
    doProcessMessage                         N      com.linbit.linstor.proto.CommonMessageProcessor:218
    lambda$processMessage$2                  N      com.linbit.linstor.proto.CommonMessageProcessor:164
    onNext                                   N      reactor.core.publisher.FluxPeek$PeekSubscriber:177
    runAsync                                 N      reactor.core.publisher.FluxPublishOn$PublishOnSubscriber:439
    run                                      N      reactor.core.publisher.FluxPublishOn$PublishOnSubscriber:526
    call                                     N      reactor.core.scheduler.WorkerTask:84
    call                                     N      reactor.core.scheduler.WorkerTask:37
    run                                      N      java.util.concurrent.FutureTask:264
    run                                      N      java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask:304
    runWorker                                N      java.util.concurrent.ThreadPoolExecutor:1128
    run                                      N      java.util.concurrent.ThreadPoolExecutor$Worker:628
    run                                      N      java.lang.Thread:834

END OF ERROR REPORT.

**Comment by ghernadi** [comment] 2020-11-09 08:15
1. Do you know what operations you did before this started to happen?
2. Does this issue persists even if you restart the controller?
3. If it does, would you mind sending me a dump of Linstor's DB (e-mail-address is in my profile)

**Comment by sribee** [comment] 2020-11-09 09:23
I haven't done any operations, I just checked for list of volumes immediately after the deployment. I have seen the same error for getting resource list also, but I didn't restart the controller. I don't have that setup any longer unfortunately, if I see the issue again, I can send the db dump. What is the command(s) to dump the db?

**Comment by ghernadi** [comment] 2020-11-09 09:42
> I don't have that setup any longer unfortunately,

Too bad. Next time that happens, the easiest way would be `linstor sos-report download` which creates a new report and downloads it to your current working directory. That report collects also additional information like `dmesg`, all ErrorReports, creates a Linstor-DB-dump, etc...

The error report you showed is `5FA8E4BB-00000-000031`, which means there are 30 other previous error reports. I guess any of those 30 should have contained a hint to the root cause. 

With the information I see here, there is not much I can do :/

**Comment by ghernadi** [comment] 2020-12-15 16:14
Sorry for the long delay. Bug was found and fixed. Will be included in the next linstor-server release.

**Comment by WanzenBug** [comment] 2021-01-13 13:37
For completeness: 

this was fixed in https://github.com/LINBIT/linstor-server/commit/2cdf3adfcbf8961b9d532a6155557b264b14192e and is available in `quay.io/piraeusdatastore/piraeus-server:v1.11.0` and later.

**Closed by WanzenBug** 2021-01-13 13:37 UTC
