### ISSUE TITLE
Allow enabling the topology feature for CSI

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/piraeus-operator#68] opened 2020-07-27 07:38 UTC
Linstor CSI supports the [CSI Topology feature](https://kubernetes-csi.github.io/docs/topology.html). However, it is disabled. See [here](https://github.com/piraeusdatastore/piraeus-operator/blob/b2f973dd5768044ef43bf7883c91c6fdd6fa6603/pkg/controller/linstorcsidriver/linstorcsidriver_controller.go#L527)

One reason why someone might want to disable this feature: https://github.com/piraeusdatastore/linstor-csi/issues/54
In short: the way it is implemented might be unsuitable for large clusters. (I have a feeling this is just a limitation in the way Linstor CSI implemented this feature, but I haven't investigated further)

Adding a new value to the CSI resource to toggle this flag shouldn't be an issue. This leaves the following questions:

#### Do we want to enable the topology feature?
My opinion: yes, its a useful feature

#### If yes, do we want it configurable?
My opinion: yes, as there are certain problems with this feature, as linked above

#### If yes, what should the default?
My opinion: Default to "yes". A default installation of the operator should provide the fullest feature set for users that just want to try it out.

Opinions @alexzhc @JoelColledge ?

**Comment by JoelColledge** [comment] 2020-07-27 07:50
I don't know much about this feature, but here are my thoughts anyway.

> Do we want to enable the topology feature?

Yes

> If yes, do we want it configurable?

Yes

> If yes, what should the default?

No. We do want to make it easy to try out the operator, but we don't want to lay traps for people who scale up with the default settings. To use this feature, the user must perform some additional steps to configure the topology information, so a user who is just trying out the operator probably won't benefit from it anyway. Also, there is some overlap between what this does and Stork and it might be confusing to have both running.

**Comment by JoelColledge** [comment] 2020-07-27 11:31
This is actually a duplicate of #48, right?

**Comment by WanzenBug** [comment] 2020-07-27 11:37
You are right.

**Comment by alexzhc** [comment] 2020-08-11 06:31
CSI topology is especially needed when provisioning pure lvm volumes, which have no magic of drbd diskless for remote attachment.

**Comment by alexzhc** [comment] 2020-08-11 10:38
People need native lvm/zvol volumes for performance applications like mysql cluster. Using stork for those pure lvm volumes is an overshoot. I would suggest leave `--feature-gates=Topology=true` by default, and then only recognize it with StorageClass parameter `placementPolicy: FollowTopology`

**Comment by WanzenBug** [comment] 2020-09-07 13:35
One thing to also mention: The current implementation of this feature in linstor-csi, while better than the old one, is by no means perfect. A stumbling block that is probably very easy to run into: The accessible topologies of a node are only ever queried on plugin start. That means that any storage pool that is later added via LINSTOR API will not show up as accessible by the node. Only a restart of the node pod would trigger another check for new storage pools.

This is a limitation of the way kubernetes chose to implement the node info collection. I have not found a good workaround for this problem yet. This led me to disable this feature by default.

**Closed** 2020-09-07 13:51 UTC
Labels: enhancement
