### ISSUE TITLE
failed to fail-over resource

### ISSUE THREAD

**Issue by yeshl** [piraeusdatastore/piraeus-operator#651] opened 2024-04-23 07:49 UTC
I0423 06:45:42.066690       1 agent.go:253] starting reconciliation
I0423 06:45:52.066708       1 agent.go:253] starting reconciliation
I0423 06:45:52.066824       1 reconcile_failover.go:137] resource 'pvc-5402447b-9617-4764-902b-93ae4cea6106' on node 'master22.host' has failed, evicting
W0423 06:46:05.985734       1 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0423 06:46:05.985738       1 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: watch of *v1.VolumeAttachment ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0423 06:46:05.985770       1 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0423 06:46:05.985738       1 reflector.go:462] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: watch of *v1.PersistentVolume ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
E0423 06:46:05.985948       1 reconcile_failover.go:141] "failed to fail-over resource" err="failed to apply node taint: Put \"https://10.96.0.1:443/api/v1/nodes/master22.host?fieldManager=linstor.linbit.com%2Fhigh-availability-controller%2Fv2\": http2: client connection lost"
I0423 06:46:05.986006       1 agent.go:253] starting reconciliation
I0423 06:46:05.986111       1 reconcile_failover.go:137] resource 'pvc-5402447b-9617-4764-902b-93ae4cea6106' on node 'master22.host' has failed, evicting
E0423 06:46:05.997341       1 reconcile_failover.go:141] "failed to fail-over resource" err="failed force detach: volumeattachments.storage.k8s.io \"csi-28b5875796ad4197fe5c795c0ce064930dc9536179e69c3d0edaaf92121ee99b\" not found"
I0423 06:46:12.066698       1 agent.go:253] starting reconciliation
I0423 06:46:12.066840       1 reconcile_failover.go:137] resource 'pvc-5402447b-9617-4764-902b-93ae4cea6106' on node 'master22.host' has failed, evicting
I0423 06:46:22.067170       1 agent.go:253] starting reconciliation
I0423 06:46:22.067312       1 reconcile_failover.go:137] resource 'pvc-5402447b-9617-4764-902b-93ae4cea6106' on node 'master22.host' has failed, evicting
I0

**Comment by WanzenBug** [comment] 2024-04-23 11:27
Closing as duplicate of https://github.com/piraeusdatastore/piraeus-ha-controller/issues/59

**Closed as not planned by WanzenBug** 2024-04-23 11:27 UTC
