### ISSUE TITLE
Feature request: CSI Topology feature gate parameter

### ISSUE THREAD

**Issue by tbykowsk** [piraeusdatastore/piraeus-operator#48] opened 2020-06-29 13:31 UTC
Please consider adding an option to set the value of [Topology feature gate](https://github.com/piraeusdatastore/piraeus-operator/blob/7008b2bd0299c772d226b1ef17fd4d4e2ee7e9d8/pkg/controller/linstorcsidriver/linstorcsidriver_controller.go#L517) parameter using a variable.

**Comment by WanzenBug** [comment] 2020-07-27 11:46
Duplicate of #68

Technically, this is the older issue, and #68 is the duplicated. However, it has more discussion, so I will close this instead.

**Closed by WanzenBug** 2020-07-27 11:46 UTC
Labels: enhancement
